### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by SerialDreams** [fragglet/ipxbox#31]
Is there a way to compile this program for windows? On that note, why are no compiled binaries provided?

**Comment by fragglet** [comment]
They're built as part of the continuous integration pipeline. The following is an illustration I hope you find useful:

![Screenshot 2023-11-16 at 4 35 18 PM](https://github.com/fragglet/ipxbox/assets/96821/85ae5fc8-501f-4ba7-884f-6baeecf2c5be)

Not much effort has been put into the Windows version since it's not an OS I use much or know very much about.

**Comment by SerialDreams** [comment]
Appreciate ya. Though, I still think it would only benefit the end-user and make things a bit more streamlined to set up a /releases page.
